const slides = [
  {
    id: 0,
    pHeader: 'Education, Institutions, Ed-tech,',
    brHeader: 'etc',
    h1Body: 'Lorem ipsum dolor sit amet, consectetur',
    brBody1: 'adipiscing elit. Praesent efficitur a purus nec',
    brBody2: 'sollicitudin.',
    brBody3: '',
  },
  {
    id: 1,
    pHeader: 'Straight to customer and',
    brHeader: 'Social Media Business',
    h1Body: 'Manage payments for your business on all',
    brBody1: 'social media without creation of any',
    brBody2: 'websites on one dashboard. Payment link is',
    brBpdy3: 'all that you need!',
  },
  {
    id: 2,
    pHeader: 'Retail Merchants',
    brHeader: '',
    h1Body: 'Convert your home delivery orders to',
    brBody1: 'Prepaid and deligh your customers with the',
    brBody2: 'flexibility of payment methods',
    brBody3: '',
  },
  {
    id: 3,
    pHeader: 'E-Commerce Businesses',
    brHeader: '',
    h1Body: 'Lorem ipsum dolor sit amet, consectetur',
    brBody1: 'adipiscing elit. Praesent efficitur a purus nec',
    brBody2: 'sollicitudin.',
    brBody3: '',
  },
  {
    id: 4,
    pHeader: 'Wholesalers and Distributors',
    brHeader: '',
    h1Body: 'Lorem ipsum dolor sit amet, consectetur',
    brBody1: 'adipiscing elit. Praesent efficitur a purus nec',
    brBody2: 'sollicitudin.',
    brBody3: '',
  },
  {
    id: 5,
    pHeader: 'Telecommunications and IT',
    brHeader: 'Company',
    h1Body: 'Lorem ipsum dolor sit amet, consectetur',
    brBody1: 'adipiscing elit. Praesent efficitur a purus nec',
    brBody2: 'sollicitudin.',
    brBody3: '',
  },
  {
    id: 6,
    pHeader: 'Utility Services Businesses',
    brHeader: '',
    h1Body: 'Lorem ipsum dolor sit amet, consectetur',
    brBody1: 'adipiscing elit. Praesent efficitur a purus nec',
    brBody2: 'sollicitudin.',
    brBody3: '',
  },
  {
    id: 7,
    pHeader: 'Logistics and Transaportation',
    brHeader: '',
    h1Body: 'Lorem ipsum dolor sit amet, consectetur',
    brBody1: 'adipiscing elit. Praesent efficitur a purus nec',
    brBody2: 'sollicitudin.',
    brBody3: '',
  },
];

export default slides;
