export {default as businessResourceLine} from './businessResourceLine.svg'
export {default as arrow} from './arrow.svg'
export {default as image1} from './image1.svg'
export {default as image2} from './image2.svg'
export {default as image3} from './arrow.svg'
export {default as next} from './next.svg'
export {default as prev} from './prev.svg'
